[project]
name = "yt-fetch"
version = "2.0.0"
description = "A interactive command line interface (CLI) for downloading YouTube videos and audio. Built with Python and yt-dlp."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mutagen>=1.48.1",
    "static-ffmpeg>=3.0",
    "tomlkit>=0.15.1",
    "yt-dlp[default,deno,curl-cffi]>=2026.8.19",
]

[project.scripts]
yt-fetch = "yt_fetch.main:main"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["yt_fetch", "yt_fetch.downloader"]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
