name: Build Wheel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.11' 

      - name: Build Python packages
        run: uv build

      - name: Upload Wheel Artifact
        uses: actions/upload-artifact@v7
        with:
          name: yt-fetch-wheel
          path: dist/*.whl